### ISSUE TITLE
Support for datetimes?

### ISSUE THREAD

**Issue by bakkdoor** [Remesh/ex_orient#4]
It looks like datetimes aren't supported, even though marco_polo does seem to support them (in the `{:long, secs}` format).

If I just pass the timestamp seconds as the value of a field to be stored, it won't store the right value in the database (I'm guessing because it expects it in the mentioned long format).
I'm getting this error:

```
** (Poison.EncodeError) unable to encode value: {:long, 1456812008}
    (poison) lib/poison/encoder.ex:339: Poison.Encoder.Any.encode/2
    (poison) lib/poison/encoder.ex:213: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:214: Poison.Encoder.Map.encode/3
    (poison) lib/poison.ex:41: Poison.encode!/2
    (ex_orient) lib/ex_orient/query_builder.ex:369: ExOrient.QueryBuilder.append_content/3
    (ex_orient) lib/ex_orient/db/crud.ex:157: ExOrient.DB.CRUD.insert/1
```

**Comment by pdilyard** [comment]
Hey! Sorry for the delay in response on this. Can you paste the code that was used to bring up this error?

It probably will never work with the `DB.insert(into: Test, content: %{time: {:long, 1456812008}})` style, as the map you pass to `content` is fed directly to `Poison` to be encoded as JSON. Try using something along the lines of: `DB.insert(into: Test, set: [time: {:long, 1456812008}])`. It's likely this won't work either, but it will give us a better jumping off point when fixing this issue.

Thanks for you patience!

**Comment by bakkdoor** [comment]
I found a way to store datetimes using just a formatted time string using 
```elixir 
DateFormat.format(date, "%Y-%m-%d %H:%M:%S", :strftime)
```

But here's a different question: Does ExOrient support storing binary data? Since it uses Poison to encode the data as JSON, what about data that isn't supported by poison? Can this be supported?
I really do need to store some binary data in the DB and would still like to use ExOrient instead of having to use marco polo directly or write my own query builder.

Thanks for your help!

**Comment by pdilyard** [comment]
It only uses Poison to encode data if you use `DB.insert(into: X, content: %{key: "value"})`. If you use `DB.insert(into: X, set: [key: "value"])`, it will use MarcoPolo in the same way you would.

**Comment by bakkdoor** [comment]
Ah cool, thanks for the info. I guess for the Date stuff, adding a Poison encoder implementation for it would make it also work with the first insert call?

**Comment by pdilyard** [comment]
That is very possible. Would love to see a PR if this is important to you, as I am very busy at work right now and will probably not have time to make this change for quite a while.

Thanks for using this lib, and please feel free to make any more issues if you have any other problems. You can also find me in the Elixir Slack channel @pdilyard
